### ISSUE TITLE
Update runtime to 3.34

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.gimp.GIMP#60]

**Comment by hfiguiere** [comment]
pygtk2 fail to build with 3.34:

```
In file included from /usr/include/pango-1.0/pango/pango.h:31,
                 from pango.override:28:
/usr/include/pango-1.0/pango/pango-engine.h:238:7: note: declared here
  238 | GType pango_engine_shape_get_type (void) G_GNUC_CONST;
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
pango.c:8650:55: error: ‘PANGO_TYPE_FONTSET_SIMPLE’ undeclared (first use in this function); did you mean ‘PANGO_TYPE_FONT_FAMILY’?
 8650 |     pygobject_register_class(d, "PangoFontsetSimple", PANGO_TYPE_FONTSET_SIMPLE, &PyPangoFontsetSimple_Type, Py_BuildValue("(O)", &PyPangoFontset_Type));
      |                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                       PANGO_TYPE_FONT_FAMILY
pango.c:8650:55: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:630: pango_la-pango.lo] Error 1
make: *** Waiting for unfinished jobs....

```

**Comment by hfiguiere** [comment]
This is bug https://gitlab.gnome.org/GNOME/pango/issues/417

That has been fixed upstream.

**Comment by MaxMilton** [comment]
Would be great to see some progress here. Anything I can do to help?

**Comment by Erick555** [comment]
@MaxMilton it should be enough to apply this patch to pygtk: https://github.com/flathub/org.glimpse_editor.Glimpse/blob/master/patches/pygtk-Drop-the-PangoFont-find_shaper-virtual-method.patch

**Comment by Erick555** [comment]
Some initial work was done so you may build on top of it: https://github.com/flathub/org.gimp.GIMP/pull/61

**Comment by hfiguiere** [comment]
Pull request submitted.
